### ISSUE TITLE
Please add Homekit support

### ISSUE THREAD

**Issue by kevinshane** [seblucas/alpine-homeassistant#3]
Hi, thanks for the awesome job, would you please add homekit? Thanks

**Comment by seblucas** [comment]
Will check the size difference and report back

**Comment by kevinshane** [comment]
hey man, I also care about the size very much too.
after I play some build based for your dockerfile, I managed to reduce the image size to around 68mb, with homekit component of cause. does it looks good to you? I also add the broadlink component as well because it seems hard to install after the builds.
I didn't test the stability for the homekit though, will test it soon and report back here.

**Comment by 2sheds** [comment]
Recent README changes include a working example for enabling HomeKit. @kevinshane, my best result with default plugins is 194 MB - which ones did you drop to reduce it to 68 MB?

**Comment by kevinshane** [comment]
hi @2sheds , the 68MB is 0.79.3 based.
The size of a v0.82.0 is 72MB(pushed to docker hub).. but the local image size is actually 219.8 MB(build size), so I think your 194MB is better :)

**Comment by seblucas** [comment]
The size reported by Docker is compressed, the size reported by `docker images` is not.

**Comment by seblucas** [comment]
I'll close this in a day or so as I think it will be answered by the information added in the README.md.
